### ISSUE TITLE
Cross-origin error in Gatsby 

### ISSUE THREAD

**Issue by BorisGiba** [FastComments/fastcomments-react#3]
I included fastcomments into my Gatsby site using this snippet:

```jsx
<FastCommentsCommentWidget
  tenantId="MY_ID"
  urlId={uniqueId}
/>
```

When running the app in development mode locally, on localhost:8000,
Whenever I access any page that has this snippet on it, I get a cross-origin error:

**Error in function Object.invokeGuardedCallbackDev in ./node_modules/react-dom/cjs/react-dom.development.js:4005**
A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information.

<img width="432" alt="fastcommentsError" src="https://user-images.githubusercontent.com/32174937/130364297-5278c999-d5a9-4e2e-b5d5-32f928da1f42.png">

What I have tried:
- lazyloading the comment section (only rendering after a button press) -> no success
- only showing comments in production mode -> pages with comment section do not load at all

Details:
- Gatsby version: 3.7.2
- React version: 17.0.2
- Fastcomments-react version: 2.0.1
- OS: Windows
- Browser: Chrome

Any idea as to why this might happen?

Edit: the tenantId "demo" works just fine. Only when I put in my own id does it stop working.

**Comment by BorisGiba** [comment]
Found the error!
The issue was that my `uniqueId` was a number, not a string.
So using `String(uniqueId)` works just fine.

**Comment by winrid** [comment]
Glad you figured it out. We'll add some defensive programming in the react library to prevent this in the future.

**Comment by BorisGiba** [comment]
No problem, thank you for responding so quickly!
